- components/wpt-results.html
The column layout right now is accomplished by flexbox and is kind of haggard. This changes the results layout to be `<table>` based and therefore all results columns will always be inline.
I deployed this to http://table-dot-wptdashboard.appspot.com/ if you want to take a look. 
TODO
> Change UI to use <table> so all columns are aligned

- components/wpt-results.html
Previously tests had no color coding (green/red). Now they do.
Check this branch out at https://results-colors-dot-wptdashboard.appspot.com
> Add pass/fail colors for tests

- components/wpt-results.html
This PR:
- Makes search faster by limiting the number of results returned
- Fixes the problem where search wouldn't update for some inputs
- Refactors all data to be stored in objects instead of arrays, then converts the data into an array for display
- Better supports missing results. Right now if you're looking at results from browser 1 and 2, if results for a test file for 1 are missing, 2's results will appear in 1's column.
TODO:
See this branch at https://search-refactor-dot-wptdashboard.appspot.com
> Search refactor

- components/wpt-results.html
This was originally meant to be included in #16 but wasn't uploaded before the PR was landed.
This also deletes two now unused methods.
> Sort specs and test results

- components/wpt-results.html
- templates/_head.html
This PR fixes #27 and adds:
- The ability to visit a path like `/css/css-align-3`
- Links on all the spec names to these pages
The UI isn't super pretty, but it gets the job done. Any feedback welcome.
Check it out: https://directory-filtering-dot-wptdashboard.appspot.com/css/css-align-3
> Directory filtering

- .gitignore
- components/test-file-results.html
- components/test-run.html
- components/wpt-results.html
- models.go
- templates/_head.html
- templates/index.html
Resolves #41 
This PR:
- Adds pages for individual test results: [example](https://pushstate-dot-wptdashboard.appspot.com/custom-elements/parser/parser-uses-constructed-element.html)
- Adds directory links that use [pushState](https://developer.mozilla.org/en-US/docs/Web/API/History_API#Adding_and_modifying_history_entries) for much quicker directory navigation (no page reload)
- Removes the underlying plumbing to select multiple directories (to simplify things for now)
- Adds directory navigation breadcrumb links to the top under search
Additional smaller changes:
- Add the `<test-run>` static component for UI simplification
- Changes all link colors to blue
- Changes font of directory names and subtest names to `monospace`
TODO:
This branch is deployed at: …
> Add test file pages that display subtest results

- .travis.yml
- browsers.json
- models.go
- run/browsers_test.py
- test_handler.go
Resolves #47
I decided to split this change out of #17 since it's ready to land and useful.
This PR:
- Adds `browsers.json`, a file listing all platforms we intend to test and display
- Splits Travis into Node and Python builds
- Adds a Python unit test that validates the values of `browsers.json`
- Changes the main `testHandler` to read `browsers.json` and display only those marked as  "initially_loaded"
> Add browser list, validation tests, and use it in TestHandler

- components/wpt-results.html
Now that all results pages act like a SPA, page view events are
no longer being sent to Google Analytics. This fixes that by
manually sending the event.
> Fix Google Analytics page tracking

- components/test-file-results.html
- components/test-run.html
- components/wpt-results.html
Fixes #19 
I was vexed for a while trying to support Safari since it would enter an infinite loop loading all the HTML imports over and over again. After a bunch of searching it looks like the problem was that we were using absolute paths:
```html
<link rel="import" href="/bower_components/polymer/polymer-element.html">
```
instead of relative paths:
```html
<link rel="import" href="../bower_components/polymer/polymer-element.html">
```
So that fixes the problem. I've verified that this works in the following browsers:
Also cc @gsnedders FYI
> Support Safari 10 and Edge 15 by fixing infinite import loop problem

- components/test-file-results.html
Fixes #65 
Since I removed the requirement that platform IDs have a regular structure in #47, test file results now don't show up on individual test pages because they were relying on that structure. 
This is a quick fix. We should have a better solution long-term, like storing the platform ID inside the TestRun.
Compare:
- https://wptdashboard.appspot.com/domparsing/DOMParser-parseFromString-html.html
- https://fix-test-file-results-url-dot-wptdashboard.appspot.com/domparsing/DOMParser-parseFromString-html.html
> Fix test file results URL building

- util/generate_testrun_index.py
This solves half of #73. The other half is regularly running it. (However I don't have plans to set that up yet, I think we should see what the demand is.)
As a side note, if we set up this script to run regularly, we then would have no need to store `TestRun`s in Datastore and could transition the site to be completely static (issue #56).
> Add script for generating TestRun index

- components/wpt-results.html
Previously when viewing a subdirectory (e.g. /css), the UI would show all test files in all subdirectories of that directory. This PR only shows immediate children of directories, so for instance, `/css` now only shows immediate subdirectories like `/css/css-grid-1`.
Preview up here:
https://limit-directories-dot-wptdashboard.appspot.com/
Fixes #57 
Fixes #60
TODO:
Performance impact on time to first usable render: -0.05%
- https://wptdashboard.appspot.com/
- https://limit-directories-dot-wptdashboard.appspot.com/ - 1.85 seconds
> Only show immediate children in directories

- run/run.py
As mentioned in https://github.com/GoogleChrome/wptdashboard/pull/62#issuecomment-322883386, adding `--run-by-dir` fixes the issue where the run stops producing results 2/3 of the way through.
> Add --run-by-dir and --no-restart-on-unexpected to Sauce

- .travis.yml
- models.go
Adds a new step to the Travis CI matrix that runs `golint`, also fixes lint errors
Fixes #12
> Add golint to Travis CI

- components/wpt-results.html
Add a simple link to the original source file on GitHub w3c/web-platform-tests
Fixes #91 
Fixes #49
> Add link to original test source file

- .travis.yml
- run/run.py
- run/run_test.py
> Py2 support

- run/run.py
Using the `./wpt` command we don't need to worry about dependencies required for running things and it passes things through as if you were calling wptrunner directly.
> Move to calling wpt helper for running tests. Fixes #122

- run/run.py
This was missed when moving things to python2 only support.
> Correcting use of write()

- run/run.py
- run/running.example.ini
In #126 the move to using |wpt run| obsoleted the need for setting the
profile as it wpt makes sure the profile is setup correctly.
> Remove the use of Firefox profile in configuration.

- components/wpt-results.html
On mobile devices, clicking on the individual tests/categories was quite hard. Increase the row height to 30px makes it a lot easier to click on it.
> Increase row height for easier clicking on mobile devices

- README.md
This is a fixup of 18c9d0016a395324f2eb65f385f5a896c499f2fc where
the file extension was omitted. At least on macOS, it doesn't work.
> Fix documentation for installing dependencies

- run/run.py
- run/running.example.ini
Via #testing, we were passing the wrong value to
--webdriver-binary for Geckodriver, causing webdriver tests
in Firefox to fail. Now that `wpt run` supports downloading
a webdriver binary itself, we can remove this option.
cc @AutomatedTester
> Remove --webdriver-binary

- util/wpt.patch
@bobholt FYI now that https://github.com/w3c/web-platform-tests/pull/7679 landed it's causing patches on WPT to fail. I'm going to land this and update all the bots.
> Remove upstreamed patch for sc metrics address

- .travis.yml
- requirements.txt
It's been renamed: https://github.com/PyCQA/pycodestyle/issues/466
> Rename pep8 to pycodestyle

- components/wpt-results.html
> Show data for test files which do not end in html or htm.

- latest_results_redirect_handler.go
- main.go
e.g.
localhost:8080/latest/chrome-63.0
302's to
https://storage.googleapis.com/wptd/b952881825/chrome-63.0-linux-summary.json.gz
localhost:8080/latest/chrome/2dcontext/building-paths/canvas_complexshapes_arcto_001.htm
302's to
https://storage.googleapis.com/wptd/b952881825/chrome-63.0-linux/2dcontext/building-paths/canvas_complexshapes_arcto_001.htm
> Add handler for /latest/{platform}[/{test}] urls

- index.yaml
https://github.com/w3c/wptdashboard/issues/161 - Need index for the hyphen-delimited behaviour of that path - worked locally since everything is indexed in the default setup.
e.g. Currently we are getting 500s on the following URL:
https://wpt.fyi/latest/chrome-63.0
> Add BrowserVersion, OSName, OSVersion indexes

- populate_dev_data_handler.go
Reverts w3c/wptdashboard#187
cc @lukebjerring reverting this since it doesn't compile:
```
/tmp/tmphxWZ24appengine-go-bin/populate_dev_data_handler.go:75: undefined: http.ErrUseLastResponse
/tmp/tmphxWZ24appengine-go-bin/populate_dev_data_handler.go:86: undefined: http.ErrUseLastResponse
```
> Revert "Add latest prod runs to populate task"

- .travis.yml
- Dockerfile
- ci_container.sh
- docs/running-ops.md
- k8s/README.md
- k8s/jenkins.yaml
- k8s/lb/ingress.yaml
- k8s/options
- k8s/service_jenkins.yaml
- run/jenkins.py
- util/ci_container_inner.sh
- util/wpt.patch
This PR introduces a number of big changes:
- Adds a `Dockerfile` for generating a container capable of running any browser of WPT we currently run
- It does not bundle a version of FF, it uses `--install-browser`
- Currently this does not include Chrome
- The whole running setup is end-to-end tested in Travis CI (FF only for now)
- Adds Kubernetes specs (in `k8s/`) for setting up a Jenkins instance (https://ci.wpt.fyi)
Future work after this lands (I will make bugs for these):
- Get Chrome running in the container (this might involve writing `--install-browser` for Chrome)
- Delete `run/run.py` once Chrome support lands
- Further investigate sharding FF builds
More context around this work is described in this comment: https://github.com/w3c/wptdashboard/issues/164#issuecomment-341172569
> Dockerize WPT runs & add Jenkins k8s specs

- util/diff_runs.py
- util/diff_runs_test.py
- util/requirements.txt
Simple number diffing for 2 different runs, leveraging the wpt.fyi/json endpoint.
Will be nice to improve this to also have some test path filters, etc.
> Add a tool for diffing runs

- docs/ui.md
Via discussion in #188, I think having stated UI design principles would help when people are submitting patches. Having somewhere to point people with stated standards is useful.
> Add UI documentation starter

- util/diff_runs.py
- util/diff_runs_test.py
Allows specific path prefixes, which is useful for comparing results of 2 runs for a given folder.
e.g. `util/diff_runs.py --before=chrome@latest --after=safari@latest /css/css-images/`
> Add test paths filtering to diff tool

- populate_dev_data_handler.go
Re-attempt at https://github.com/w3c/wptdashboard/pull/187, which failed because it used a golang 1.7 feature. This PR is identical, but manually replicates the ErrUseLastResponse behaviour.
> Add latest prod runs to populate task

- components/wpt-results.html
The test_handler.go produces a spec list for a given sha, and doesn't actually check whether each browser exists for the given sha (which is determined by the /api/run returning a 404).
Fixes https://github.com/w3c/wptdashboard/issues/232
> Filter non-200 fetches

- components/results.html
- components/test-file-results.html
- components/wpt-results.html
Fix for https://github.com/w3c/wptdashboard/issues/235, which is caused when the reload of an individual-results page does not trigger the (newly added) api fetch for the TestRun JSON.
> Add shared results polymer base class

- components/wpt-results.html
- templates/index.html
- test_handler.go
Continues to use the resources from /api/run, but allows the component to have the runs specified as inline JSON (as was the previous impl), which will be needed for re-using the component.
> Revert wpt-results to supporting test-runs being inlined.

- api_handlers.go
- test_handler.go
- test_run_handler.go
- util.go
Moves 'GetBrowserNames' into a util.go for re-use, and persists the result in memory.
> Persist loaded browser names

- CONTRIBUTING.md
Per https://github.com/w3c/wptdashboard/issues/118#issuecomment-330689900
The guidance around copyright headers is still in need of updating.
> Remove the CLA section of CONTRIBUTING.md

- components/wpt-runs.html
Currently wrong order due to using a set.
> Sort test-runs browsers alphabetically.

- api_handlers.go
- main.go
- populate_dev_data_handler.go
- test_run_handler.go
Also improves some handler naming (too general for methods across the namespace) and fixes a bug with the populate_dev_data script (which is being deleted in https://github.com/w3c/wptdashboard/pull/248 anyway).
> Migrate /test-runs POST to /api/runs POST

- README.md
In the "Running" section of README.md: 
./util/docker/dev.sh => ./util/docker-dev/run.sh
> Fix path to ./util/docker-dev/run.sh

- api_handlers.go
- util/add_production_run.py
This is important for the add_production_run script to be able to copy old runs and not have them dated to the moment of copy.
> Add 'retroactive' param to allow adding a historical run

- util/pull_run_into_static.py
Without this change, requests for platform summary data result in:
WARNING:root:Got unexpected non-redirect result 200
> Update path: /json -> /results in pull_run_into_static.py

- Dockerfile.base
- Dockerfile.jenkins
The apt-get virtualenv is to make sure it is in the PATH as an executable.
Moving these dependencies to base because when running a dev container we want to be able to run wpt run.
/cc @mdittmer
> Move apt-get installs to base and install virtualenv

- run/jenkins_test.py
Eventually `run.py` and `run_test.py` will go away (once #205 is fixed).
> Duplicate run_test as jenkins_test (sans N/A tests)

- browsers.json
Adds Chrome 64.0 in browsers.json since it is the current canary.
cc/ @lukebjerring
> chrome 64.0

- run/shas.py
> Follow only the first parent commit upon seeing a merge commit. This option can give a better overview when viewing the evolution of a particular topic branch, because merges into a topic branch tend to be only about adjusting to updated upstream from time to time, and this option allows you to ignore the individual commits brought in to your history by such a merge.
> Add --first-parent filter to first-SHA-of-day check

- api_handlers.go
- util.go
- util_test.go
This actually highlighted a bug where a function was re-using a global variable unintentionally (see getLastCompleteRunSHA).
> Add IsBrowserName util method, and test it.

- components/wpt-runs.html
- package.json
An eslint-plugin-html v4 has been published, which broke builds on
Travis. Lock the version to v3 together and also fix the "standard"
version at the same time.
Update components/wpt-runs.html to satisfy the lint.
> Specify eslint-plugin-html version to fix lint

- api_handlers.go
- params.go
- params_test.go
- run_diff.go
- run_diff_test.go
Progresses https://github.com/w3c/wptdashboard/issues/301
Uses a git-inspired filtering charset param.
?filter=[A][C][D]
A = Added
C = Changed
D = Deleted
> Add support for filtering change types when diffing

- components/runs.html
- components/wpt-runs.html
- params.go
- templates/test-runs.html
- test_handler.go
- test_run_handler.go
For the index/homepage, this changes 4 /api/run fetch requests to a single /api/runs request.
For /test-runs, it defers the data-store fetch to the request from the client, greatly simplifying the Go code, with minimal effect to latency.
Running here:
https://20171127t105621-dot-wptdashboard.appspot.com
Note that this also allows for a bigger fetch of test-runs, which is related to https://github.com/w3c/wptdashboard/issues/73 - e.g.:
https://20171127t105621-dot-wptdashboard.appspot.com/test-runs?max-count=500
> Migrate /test-runs and / to use /api/runs

- api_handlers.go
Progresses https://github.com/w3c/wptdashboard/issues/301
POST allows an arbitrary JSON blob instead of the 'after' param as needed for the GET request.
This can be combined with https://github.com/w3c/wptdashboard/pull/303 to support a POST request after a test run which would be able to surface regressions.
>  Add POST method for /api/diff

- Dockerfile.base
- Dockerfile.dev
- Makefile
This enables us to create sub-packages that depend on each other using `go get`'s idioms for package management.
E.g.,
```go
// repo-root/frobinator/frobinate.go
package frobinator;
import base "github.com/w3c/wptdashboard"
var runs []base.TestRun
```
```go
// repo-root/frobinator/run/main.go
package main;
import base "github.com/w3c/wptdashboard"
import "github.com/w3c/wptdashboard/frobinator"
func main() {
var f frobinator.Frobinator
var runs []base.TestRun
// ...
}
```
> Package go code according to repo where it lives

- Dockerfile.base
This is needed to fix the fact that GoogleCloudPlatform/protoc-gen-bq-schema cannot build unless it's pulled into the Go path.
Note that I have concerns with the first commit for this PR, which while replicating the intended behaviour, leaves us in a state where we have a copy of protoc-gen-bq-schema both in $GOPATH/src/ and in the /home/jenkins (git root) dirs.
I think it best that this fix be followed with a tweak to the Makefile for wptdashboard to expect the executable to be built in the Go src dir, to prevent mismatches in future.
> Use 'go get' instead of git clone for bq-schema build

- webapp/components/test-file-results.html
Redoes the changes from https://github.com/w3c/wptdashboard/pull/319/commits/8c0d31fa6c7d0f33d06845cf77c3737dfeadb768, which got muddled via a bunch of merges.
> components/test-file-results.html: use template strings

- webapp/params.go
- webapp/params_test.go
- webapp/run_diff.go
- webapp/test_handler.go
While, for a diff, we generally want only things that have changed, this makes the totals/summary numbers look a bit strange on wpt.fyi. 
Including 'U' in the filter means that the total numbers of tests match, but the number of differences is unchanged.
> Add diff filter U for unchanged

- run/shas_test.py
Better fix than https://github.com/w3c/wptdashboard/pull/331 for the currently-broken build.
> Run an unshallow fetch during test

- webapp/anomaly_handler.go
- webapp/interop_handler.go
- webapp/main.go
- webapp/templates/anomalies.html
- webapp/templates/interoperability.html
mdittmers [metrics demo](https://metrics5-dot-wptdashboard.appspot.com/metrics/) is one of two views from the [metrics design](https://docs.google.com/document/d/1MZRF3EdpMG0pLNI99jEj-pBITbqWKYMyJC7Ga8NtZ88/edit), which intends to add a view to show tests broken down by the number of browsers they pass in.
There are two views:
- a list of tests that pass in some, but not all, browsers
- the view demo'd above, i.e. tests broken down by interoperability
This PR adds placeholder endpoints for these views, and the main objective of the PR is to pick a name for each view.
> Give names to (and add) interop views

- util/docker-dev/web_server.sh
This is needed to avoid a bug in AppEngine's Datastore API, where 2 different code paths (Key creation and Entity Put) use a different default/empty App ID ("" and "None" respectively).
We use the remote_api code from populate_dev_data.go in https://github.com/w3c/wptdashboard/pull/347
> Set an explicit App ID for local instance

- metrics/models.go
- metrics/run/collect_metrics.go
- metrics/storage/storage.go
The interface is now cleaner and allows for multiple implementations. This is illustrated by providing and leveraging a BigQuery implementation (in addition to the existing Datastore-metadata + CloudStorage-data implementation).
> Abstract storage interface and push results to GCS + BQ

- run/run.py
- run/run_test.py
- run/shas.py
Supporting work for: 
> KR: wpt.fyi always shows results for the same wpt commit (P2)
This allows a remote test runner machine to specify which commit SHA of wpt should be run. Next, we need to decide on how to establish the "source of truth", ie. _what_ determines that SHA and then _where_ that information lives. 
To run the tests directly: 
```
docker exec -it -u $(id -u $USER):$(id -g $USER) wptd-dev-instance python run/run_test.py
```
> run/run.py: support providing an explicit wpt commit sha

- metrics/models.go
- metrics/models_test.go
- metrics/storage/storage.go
There are a couple different golang examples, and I much prefer this one (more explicit, simpler to re-use).
> Rename sorting handlers

- webapp/components/wpt-results.html
- webapp/run_diff.go
- webapp/test_handler.go
Adds support for specifying the before+after params using base64 encoded TestRun models, which can be spoofed (or, rather, passed in from somewhere other than the wpt.fyi datastore).
See https://github.com/w3c/wpt-pullresults/pull/54 for further context around making an arbitrary TestRun from the results of a Travis Job.
> Support base64-encoded test runs when diffing

- metrics/storage/storage.go
Without reversing the data-write+metadata-write ordering, the metadata-write fails (and hence metrics data collection fails).
> Metrics=>GCS: Write data, then update gzip metadata

- webapp/app.yaml
Currently they break deployment due to their size, and are unused in production.
> Ignore populate_dev_data files when deploying

- git/git-deploy
The script simply picks a version-name to pass to AppEngine, which helps with readability, and deleting old versions.
Staging (default):
--version=[Git repo user]-[Git branch name]
Prod (-p):
--version=[Git repo short-SHA]
When deploying with -p, checks that the repo user is w3c; if not, double-checks with the user.
> Add deploy helper-script

- run/run_test.py
Patch is a built-in method for achieving the same thing.
> use unittest.mock.patch to undo ctor mocking

- metrics/run/collect_metrics.go
- shared/fetch_runs.go
- util/populate_dev_data.go
And, drive-by fix a loop-pointer-reuse bug which meant that all the runs were saving as 'safari'.
> Include latest production run in populate_dev_data

- Makefile
- README.md
- util/docker-dev/dev_data.sh
Leverages the populate_dev_data.go in docker, to avoid issues (fixes https://github.com/w3c/wptdashboard/issues/378).
For compatibility with docker-external execution, this script leverages the `$GOOGLE_APPLICATION_CREDENTIALS` variable, copying the file into docker.
> Add script for using populate_dev_data.go in docker

- webapp/anomaly_handler.go
- webapp/components/anomalies.html
- webapp/index.yaml
- webapp/templates/anomalies.html
Running at https://lukebjerring-interoperability-anomalies-dot-wptdashboard.appspot.com/interop/anomalies
First iteration is a slow-loading, flat list of all tests which pass in some, but not all, browsers, with no browser-specific views.
`/interop/anomalies` (no params) will show a list of anomalies (test that fail in at least one, but not all, browsers).
`/interop/anomalies?browser=[browser]` will show tests that **fail** in that browser, but not in all browsers.
> List all anomaly tests on the anomalies page.

- webapp/components/path-part.html
- webapp/components/wpt-results.html
This PR fixes 2 issues with the path-part:
1) `navigate` was dropped in translation, so pages are fully reloading.
2) The `path-part` displayed text (relative path) is not updated when `navigate` occurs.
Forwarding the `navigate` event requires binding `this` correctly (or, changing the function).
For the Polymer property to automagically update, we need the compute function to depend on the `path` property (since it can't tell from the function body that it depends on `this.path`.
> Fix bug with stale path-part

- .gitmodules
- Dockerfile.base
- Makefile
We (barely) depend on this (small) external lib, and it's breaking us whenever it changes, so I'm plonking it in the `vendor` path. 
Some reading to explain vendor path: https://golang.org/cmd/go/#hdr-Vendor_Directories
> Vendor protoc-gen-bq-schema

- Makefile
- run/run.py
- run/run_test.py
> Derive and include a "commit_date" for new TestRun entities. Ref gh-154

- webapp/components/wpt-results.html
Recent changes in the surrounding interface have obviated the need for the caveat in this banner element.
> Remove superflous banner

- webapp/util.go
Previously, data describing the available browsers was not loaded until
the web server handled a request which required it. Subsequent requests
were intended to re-use the result of this operation, persisted as
global application state.
That strategy was susceptible to a race condition: if the initial
request that triggered data loading was quickly followed by a similar
request, the loading logic would be executed a second time, and the
resuting in-memory representation would include two entries for each
available browser.
Re-factor the internals to load the browser data at module
initialization time (e.g. before any requests are received).
> Load browser config. data during initialization

- .travis.yml
The TravisCI documentation reads [1]:
> When one of the build commands returns a non-zero exit code, the Travis CI build runs the subsequent commands as well, and accumulates the build result.
Express disparate test commands as distinct items in an array within the TravisCI "script" configuration, ensuring that any failure causes the build to be labeled as "failing" (as opposed to only recognizing the result of the final command).
[1] https://docs.travis-ci.com/user/customizing-the-build/
This depends on gh-480
> Configure TravisCI builds to report test failures

- run/run.py
- run/run_integration_test.py
This may occur when the WPT CLI process fails due to factors other than failing tests (e.g. a misconfigured system or a network outage).
Testing this fix required extending the test code a bit. I'm submitting that in a dedicated commit to help delineate things.
> run.py: handle cases where WPT "raw log" is empty

- run/run.py
This is intended as a temporary fix to allow the webrtc tests in chrome to call getUserMedia without failing out.
> add command line flags for webrtc

- run/run.py
- webapp/browsers.json
This also includes an update to `browsers.json` which adds Firefox 58.0
> Always use the firefox binary in running.ini

- src/scripts/validate-wpt-results.py
- test/validate_wpt_results_test.py
Previously, datasets which omitted results for some tests were
considered acceptable and subsequently uploaded to the web. The
underlying issues which motivated that design have been resolved, so the
project may be in a position to reject any incomplete datasets.
However, due to the imprecise nature of the previous validation
strategy, the actual completeness levels for certain browser
configurations are not well understood. Specifically, reports for
browsers which are mediated by the Sauce Labs service may continue to be
incomplete.
Decrease the threshold for missing tests to zero percent during results
validation. Maintain the prior threshold of two percent during results
uploading.
This configuration will surface any persisting issues with
incompleteness in the build system's web …
> Report on any incomplete result sets

- provisioning/configuration/roles/web-browsers/tasks/main.yml
@kereliuk  We've fallen a few versions behind in Chromedriver. Nothing in the change log suggests there is any reason to wait, but there are a few fixes that might improve accuracy. Do you think this is good to go?
> Update to latest version of Chromedriver

- src/master/master.cfg
- src/scripts/upload-wpt-results.py
- test/upload_wpt_results_test.py
This is intended to resolve gh-572. @Hexcles I believe that this extension is only relevant for the new results receiver. Is that right? Or should I amend this patch with an enhancement for the `wpt-legacy-wpt-results.py`?
> Include "labels" in payload sent to new receiver

- src/master/master.cfg
- src/master/wpt_chunked_step.py
The legacy results receiver required the date of the git revision under
test. Since this project no longer interfaces with that receiver, the
date no longer need to be tracked internally.
> Remove unnecessary property

- provisioning/configuration/roles/buildbot-worker/handlers/main.yml
- provisioning/configuration/roles/buildbot-worker/tasks/main.yml
- provisioning/configuration/roles/buildbot-worker/tasks/unattended_upgrades.yml
- provisioning/configuration/roles/buildbot-worker/templates/buildbot-worker.service.j2
- provisioning/configuration/roles/buildbot-worker/vars/main.yml
- provisioning/configuration/roles/web-browsers/tasks/main.yml
- src/scripts/reboot-if-present.sh
Ensure that the workers regularly download and install security patches.
This requires system reboot, which must be triggered indirectly in order
to avoid interrupting ongoing results collections.
---
This is intended to resolve gh-580. Applying it requires restarting the worker
processes. In order to avoid invalidating ongoing results collection, I'm going
to defer merging and deploying until no collection is taking place.
> Enable unattended upgrades and nightly cleanup

- provisioning/configuration/roles/buildbot-master/tasks/main.yml
- src/master/master.cfg
- src/scripts/get-wpt-revision.py
Retrieve revisions of WPT in which to run tests from the wpt.fyi "revision announcer."
No change in operation.
This should resolve gh-591.
This change introduces no new dependencies.
> Integrate with wpt.fyi "revision announcer"

- src/master/wpt_run_step.py
As of [1] (merged on 2018-09-24), the WPT CLI enables the "headless"
mode of Chrome and Firefox by default. This mode is more convenient for
contributors running the tests from their development system, but it
also relies on functionality which is not enabled during typical usage
of the browsers.  Results collected in this mode are therefore less
authentic than results collected using a virtual display.
@jgraham commented on this in [2]:
> unless we have some reasonable assurance that headless mode matches
> non-headless in all cases (e.g. the relevant browser running both
> configurations in CI with identical results) I don't think we should
> enable it for wpt.fyi-ingested runs.
That issue includes evidence that the results are not equivalent,
meaning "headless" mode is not appropriate …
> Opt-out of "headless" mode

- provisioning/configuration/roles/buildbot-worker/tasks/darwin.yml
- src/master/browsers.json
- src/master/master.cfg
- src/scripts/install-browser.sh
- src/scripts/safari-disable-popup-blocker.sh
- src/scripts/safari-enable-automation.sh
This project was previously extended with support for collecting results
from Apple Safari Technology Preview via a worker running on a macOS
system. Extend the system to also support the stable release of Apple
Safari.
Previously, a single build step installed Safari Technology Preview and
enabled remote automation. Because the stable release of Safari is
bundled with the operating system, it cannot be installed. It does
require explicit enabling of remote automation, however. Refactor the
two operations into distinct build steps in order to support both
browsers.
Safari Technology Preview enables the "Develop" UI menu by default, so
the automation script could interact with it immediately. The menu is
not present in the default configuration of Safari. Add logic to ensure
the menu is …
> Collect results from stable Safari locally

- src/master/browsers.json
This project now collects results from Safari 12 via an
internally-managed macOS system. Results from that release are more
relevant to this project, so the overhead of maintaining integration
with the Safari 11.1 browser offered by Sauce Labs is no longer
justified.
Update the configuration so that the Buildbot build master no longer
creates jobs for Safari 11.1 via Sauce Labs.
> Remove Safari 11.1

- src/master/master.cfg
- src/scripts/get-wpt-revision.py
This project recently experienced a failure because wpt.fyi was
temporarily unavailable [1]. It has since been confirmed that
intermittent outages are expected [2], so the system should tolerate the
condition by retrying failed requests for a short period.
[1] https://github.com/web-platform-tests/results-collection/issues/632
[2] https://github.com/web-platform-tests/wpt.fyi/issues/802
> Tolerate temporary unavailability of wpt.fyi

- src/master/browsers.json
Edge 44.17763.1.0 / EdgeHTML 18.17763 is available on Sauce Labs.
This is the latest stable version of Edge, and testing it will help validate
the setup for Edge on Azure Pipelines:
https://github.com/web-platform-tests/wpt/issues/14836
> Switch from testing Edge 17 to 18
