web-platform-tests/results-collection

.gitignore
.travis.yml
CONTRIBUTING.md
README.md
components/wpt-results.html
package.json

Add Standard JS linting and travis.yml, fix new lint errors

---

components/wpt-results.html

Add JS method comments, rename specs to specDirs

---

templates/_head.html
templates/about.html

Add more exposition to /about

---

CONTRIBUTING.md

Add license header guidelines to CONTRIBUTING.md

---

.travis.yml
requirements.txt
run/browsers_test.py

Add Python linting

---

README.md

Document in README how to access data

---

components/wpt-results.html

Via discussion in #107.
See it here: https://caveat-dot-wptdashboard.appspot.com

Add caveat on results pages

---

components/wpt-results.html

drop trailing slash from non-root paths when setting new `this.path`

---

run/run.py

pass flag to wptrunner for installing fonts

---

README.md
run/run.py

I have added documentation on how to run tests and updated error messages to be more meaningful.

Better setup documentation and errors

---

run/running.example.ini

Remove now unused wptrunner lines from config

---

requirements.txt

If this isn't done you will get an error if following the current README

Uncomment google-cloud requirement

---

components/test-run.html
components/wpt-results.html
templates/index.html
test_handler.go
test_handler_test.go

Supercedes https://github.com/w3c/wptdashboard/pull/181 for https://github.com/w3c/wptdashboard/issues/172

Add support for ?run=[SHA]

---

browsers.json

Fix #112: update Safari to Safari 11

---

run/jenkins.py
util/ci_container_inner.sh

Hoping this works on the jenkins build. If not, we can revert :/
cc/ @jeffcarp

command line flags and chmod for webrtc

---

components/wpt-runs.html

Resolves https://github.com/w3c/wptdashboard/issues/208

Sort runs by created date

---

about_handler.go
main.go
models.go
populate_dev_data_handler.go
results_redirect_handler.go
results_redirect_handler_test.go
test_handler.go
test_handler_test.go
test_run_handler.go

Done with the command:
find . -name \*.go -print | xargs gofmt -w

gofmt all files

---

test_handler.go

SHA order seems incorrect and results are showing from Sept.

Revert https://github.com/w3c/wptdashboard/pull/199

---

components/wpt-runs.html

Running at https://20171116t135329-dot-wptdashboard.appspot.com/test-runs

Add some date information to the /test-runs UI

---

components/test-file-results.html

Fixes https://github.com/w3c/wptdashboard/issues/258
/cc @Hexcles

Restore the _testFileChanged polymer hook

---

Makefile

Add gofmt check to go_lint rule

---

util/add_production_run.py
util/generate_testrun_index.py
util/pull_run_into_static.py

Contributes to https://github.com/w3c/wptdashboard/issues/229
cc @Hexacles

Migrate some util python scripts to python2

---

run/jenkins.py
run/run.py
test_run_handler.go

Contributes to resolving https://github.com/w3c/wptdashboard/issues/251

Migrate from POST /test-runs to POST /api/run

---

run/jenkins.py

Better code quality, same thing

---

components/runs.html
components/test-file-results.html
components/wpt-results.html
components/wpt-runs.html

Running here:
https://20171122t111259-dot-wptdashboard.appspot.com

Rename 'ResultsBase' and refactor the wpt-runs element to re-use it

---

api_handlers.go
util.go

As an aside - Travis CI says the build is passing; that needs to be fixed.

Fix bad merged state

---

git/hooks/pre-push
util/logging.sh

Fairly easy to make tweaks locally that, for example, fix lint, and then run push without committing them. This just checks that a git diff has no output (and can be bypassed with a Y confirmation)

Check for local changes in git before pushing

---

run_diff.go

Not sure how the newline wound up in the database (should probably have some validation?)

Improve error message and handle trailing newline

---

webapp/components/wpt-results.html

Minor nuisance, but improves the appearance somewhat :)

Omit the slash for missing tests

---

webapp/components/test-run.html

Date is epoch, sha is 'diff' (placeholder, since it's required)

Don't show SHA/date for diff column

---

webapp/main.go

Improves documentation of the endpoints that exist in the one place that they're exhaustively listed.

Add some comments to the wpt.fyi paths

---

webapp/components/test-file-results.html
webapp/components/wpt-results.html
webapp/components/wpt-runs.html

- There's no semantic value to prefixing methods with `_`. If privacy, or capability control is necessary, then a computed property (in the ES sense) using a Symbol is the appropriate pattern. 
- Reorganized class definitions such that methods are defined in this order: `compute*`, `async ...`, miscellaneous. 
- Removed unused code
- Eliminated unnecessary wrapper method
- Always use blocks

Various fixups to webapp/components/* files

---

metrics/naming.go
metrics/naming_test.go

Used in the [near future](https://github.com/mdittmer/wptdashboard/pull/3)

Add GetDatastoreKindName helper

---

webapp/components/test-file-results.html
webapp/components/wpt-results.html
webapp/components/wpt-runs.html

This contains the same commit that was previously landed and reverted, as well as a revision commit that "reverts" the dir/file drill down display code.

Various fixups to webapp/components/* files, Revised!

---

metrics/run/collect_metrics.go

... endpoint for pulling data in metrics collection code

Switch to fast, public (unauthenticated) GCS

---

metrics/compute/compute.go
metrics/run/collect_metrics.go

Fixes https://github.com/w3c/wptdashboard/issues/356
e.g. output: https://pantheon.corp.google.com/storage/browser/wptd-metrics/1511983599-1511983639?project=wptdashboard&organizationId=433637338589

Fix loop-pointer re-use bug

---

run/run_test.py

Related to https://github.com/w3c/wptdashboard/pull/377, hoping to get green-ness in Travis.

@mock.patch more stuff

---

webapp/components/interop.html
webapp/interop_handler.go
webapp/templates/interoperability.html

This is essentially minor tweaks to get https://github.com/mdittmer/wptdashboard/pull/3 sync'd with the current state of WPTD.
Running @ https://lukebjerring-interop-dot-wptdashboard.appspot.com/interop/

Add a first-cut implementation of /interop

---

Makefile

Fixes https://github.com/w3c/wptdashboard/issues/416
cc @Hexcles

Init submodule as part of Makefile rule

---

util/populate_dev_data.go

Noticed these were incorrect while writing https://github.com/w3c/wptdashboard/pull/408

Fix static data paths

---

webapp/components/anomalies.html
webapp/components/interop.html
webapp/components/wpt-results.html

The referenced issue on GitHub.com has been closed in favor of another.
Update the hyperlink to instead reference the open issue.

Update references to feature tracking ticket

---

webapp/main_test.go

Fixes https://github.com/w3c/wptdashboard/issues/341

Add main_test.go

---

.gitignore
.travis.yml
webapp/.eslintrc.json
webapp/README.md
webapp/app.yaml
webapp/bower.json
webapp/components/anomalies.html
webapp/components/interop.html
webapp/components/path-part.html
webapp/components/runs.html
webapp/components/test-file-results.html
webapp/components/test-run.html
webapp/components/wpt-results.html
webapp/components/wpt-runs.html
webapp/package.json
webapp/test/fixtures/passrates.json
webapp/test/interop.html
webapp/test/path-part.html
webapp/test/runs.html
webapp/test/test-file-results.html
webapp/test/test-run.html
webapp/wct.conf.json

wip: preliminary travis testing

---

metrics/storage/storage.go

Fixes #435.
This is a copy of https://github.com/lukebjerring/wptdashboard/commit/30e4fe4177e4a33edabd5ad48e0a77b21989d508  which was used to upload https://storage.cloud.google.com/llbj-wptd.appspot.com/1518032480-1518032513/chrome-failures.json.gz (verified actually gzipped).

Fix gzippin' bug

---

metrics/run/collect_metrics.go

Towards #433
@rwaldron PTAL for comprehensiveness, readability, clarity, etc..
@lukebjerring PTAL for any inaccuracies (i.e., has anything changed that makes these docs out of date?).

Add documentation header to collect_metrics.go

---

run/report.py
run/report_test.py
run/run.py
run/run_integration_test.py

This is intended to resolve gh-465

run.py: Implement `--partial-threshold` argument

---

run/run.py
run/run_integration_test.py

Previously, `run.py` was extended to ensure that the actual result set
described the expected number of tests (within some threshold). This was
implemented via the `--list-tests` flag provided by the WPT CLI.
Unfortunately, this functionality requires that the web browser under
test be installed on the local system. This is not the case when running
tests remotely using WebDriver, so the new validation logic would fail
in those cases.
The same information can be retrieved from a previously-unused output
stream (the "raw log") provided by WPT during test running.
Re-implement results validation to instead inspect the structured output
of the test run itself.
This is intended to resolve gh-472.

run.py: Re-implement results validation

---

util/commands.sh
util/docker-dev/dev_auth.sh
util/docker-dev/dev_data.sh
util/docker-dev/run.sh
util/docker-dev/web_server.sh

This doesn't change anything about the way these scripts work, just a bit of organization and code sharing.

Cleanup util/* docker scripts

---

run/run.py

Commit messages:
run.py: Report on missing tests & remove temp data
With the introduction of the "chunked execution" behavior, `run.py`
began generating intermediate results files for each test run (which
were subsequently compiled to create the complete test report). This
allowed for some additional forensics because operators could later use
those files to compare the tests that actually ran in a given chunk with
the tests that were expected to run. Unfortunately, this also
significantly increased the amount of disk space required to store each
result set.
Expand `run.py` to output information on "missing tests" for each
"chunk" and to remove all intermediate data files once the results have
been successfully reported.
---
run.py: enhance logging
Use the Python built-in `logging` module …

run.py: Improve logging

---

src/master/master.cfg
src/scripts/upload-wpt-results.py
test/upload_wpt_results_test.py

Guard against race condition during upload

---

requirements.txt
src/scripts/get-binary-url.py
src/scripts/read-browser-version.py

Mostly to update `requests` to fix a security vulnerability. Also update `pycodestyle` by the way.

Upgrade pypi packages
